Small changes + Change UserInfo and Pass
cristisocaci/EarlyBirdAPI pull request #13
Opened 2021-04-13 19:30 UTC by cristian-nicolae

2021-04-13 20:25 UTC, cristisocaci requested changes

2021-04-13 20:25 UTC, cristisocaci commented on EarlyBird.API/Controllers/UsersController.cs
> +                if (!claimIdMatches(usersService.GetById(id).Id) && !isUserAdmin())
Please simplify this

2021-04-13 20:26 UTC, cristisocaci approved these changes

2021-04-18 09:10 UTC, flaviuvr approved these changes

2021-04-18 09:10 UTC, merged